# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AgentMenu_Dialog_AddProperty.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_AddProperty(object):
    def setupUi(self, Dialog_AddProperty):
        Dialog_AddProperty.setObjectName("Dialog_AddProperty")
        Dialog_AddProperty.resize(667, 437)
        Dialog_AddProperty.setStyleSheet("background-color: rgb(245, 250, 254);")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Dialog_AddProperty)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_title = QtWidgets.QLabel(Dialog_AddProperty)
        font = QtGui.QFont()
        font.setFamily("PT Root UI Bold")
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_6.addWidget(self.label_title)
        self.LineEdit_title = LineEdit(Dialog_AddProperty)
        self.LineEdit_title.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"TextEdit,\n"
"PlainTextEdit {\n"
"    padding: 2px 3px 2px 8px;\n"
"}\n"
"\n"
"LineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"LineEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border-bottom: 1px solid #009faa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}\n"
"")
        self.LineEdit_title.setObjectName("LineEdit_title")
        self.verticalLayout_6.addWidget(self.LineEdit_title)
        self.label_des = QtWidgets.QLabel(Dialog_AddProperty)
        font = QtGui.QFont()
        font.setFamily("PT Root UI Bold")
        font.setPointSize(12)
        self.label_des.setFont(font)
        self.label_des.setObjectName("label_des")
        self.verticalLayout_6.addWidget(self.label_des)
        self.LineEdit_des = LineEdit(Dialog_AddProperty)
        self.LineEdit_des.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"TextEdit,\n"
"PlainTextEdit {\n"
"    padding: 2px 3px 2px 8px;\n"
"}\n"
"\n"
"LineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"LineEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border-bottom: 1px solid #009faa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}\n"
"")
        self.LineEdit_des.setObjectName("LineEdit_des")
        self.verticalLayout_6.addWidget(self.LineEdit_des)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_bed = QtWidgets.QLabel(Dialog_AddProperty)
        font = QtGui.QFont()
        font.setFamily("PT Root UI Bold")
        font.setPointSize(12)
        self.label_bed.setFont(font)
        self.label_bed.setObjectName("label_bed")
        self.verticalLayout.addWidget(self.label_bed)
        self.LineEdit_bed = LineEdit(Dialog_AddProperty)
        self.LineEdit_bed.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"TextEdit,\n"
"PlainTextEdit {\n"
"    padding: 2px 3px 2px 8px;\n"
"}\n"
"\n"
"LineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"LineEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border-bottom: 1px solid #009faa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}\n"
"")
        self.LineEdit_bed.setObjectName("LineEdit_bed")
        self.verticalLayout.addWidget(self.LineEdit_bed)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_bath = QtWidgets.QLabel(Dialog_AddProperty)
        font = QtGui.QFont()
        font.setFamily("PT Root UI Bold")
        font.setPointSize(12)
        self.label_bath.setFont(font)
        self.label_bath.setObjectName("label_bath")
        self.verticalLayout_2.addWidget(self.label_bath)
        self.LineEdit_bath = LineEdit(Dialog_AddProperty)
        self.LineEdit_bath.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"TextEdit,\n"
"PlainTextEdit {\n"
"    padding: 2px 3px 2px 8px;\n"
"}\n"
"\n"
"LineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"LineEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border-bottom: 1px solid #009faa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}\n"
"")
        self.LineEdit_bath.setObjectName("LineEdit_bath")
        self.verticalLayout_2.addWidget(self.LineEdit_bath)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_size = QtWidgets.QLabel(Dialog_AddProperty)
        font = QtGui.QFont()
        font.setFamily("PT Root UI Bold")
        font.setPointSize(12)
        self.label_size.setFont(font)
        self.label_size.setObjectName("label_size")
        self.verticalLayout_3.addWidget(self.label_size)
        self.LineEdit_size = LineEdit(Dialog_AddProperty)
        self.LineEdit_size.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"TextEdit,\n"
"PlainTextEdit {\n"
"    padding: 2px 3px 2px 8px;\n"
"}\n"
"\n"
"LineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"LineEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border-bottom: 1px solid #009faa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}\n"
"")
        self.LineEdit_size.setObjectName("LineEdit_size")
        self.verticalLayout_3.addWidget(self.LineEdit_size)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_price = QtWidgets.QLabel(Dialog_AddProperty)
        font = QtGui.QFont()
        font.setFamily("PT Root UI Bold")
        font.setPointSize(12)
        self.label_price.setFont(font)
        self.label_price.setObjectName("label_price")
        self.verticalLayout_4.addWidget(self.label_price)
        self.LineEdit_price = LineEdit(Dialog_AddProperty)
        self.LineEdit_price.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"TextEdit,\n"
"PlainTextEdit {\n"
"    padding: 2px 3px 2px 8px;\n"
"}\n"
"\n"
"LineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"LineEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border-bottom: 1px solid #009faa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}\n"
"")
        self.LineEdit_price.setObjectName("LineEdit_price")
        self.verticalLayout_4.addWidget(self.LineEdit_price)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_seller = QtWidgets.QLabel(Dialog_AddProperty)
        font = QtGui.QFont()
        font.setFamily("PT Root UI Bold")
        font.setPointSize(12)
        self.label_seller.setFont(font)
        self.label_seller.setObjectName("label_seller")
        self.verticalLayout_5.addWidget(self.label_seller)
        self.LineEdit_seller = LineEdit(Dialog_AddProperty)
        self.LineEdit_seller.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"TextEdit,\n"
"PlainTextEdit {\n"
"    padding: 2px 3px 2px 8px;\n"
"}\n"
"\n"
"LineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"LineEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border-bottom: 1px solid #009faa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}\n"
"")
        self.LineEdit_seller.setObjectName("LineEdit_seller")
        self.verticalLayout_5.addWidget(self.LineEdit_seller)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PushButton_create = FilledPushButton(Dialog_AddProperty)
        self.PushButton_create.setStyleSheet("OutlinedPushButtonBase,\n"
"OutlinedToolButtonBase {\n"
"    background-color: transparent;\n"
"    border: 1px solid transparent;\n"
"    padding: 6px 10px 6px 10px;\n"
"    color: black;\n"
"    outline: none;\n"
"}\n"
"\n"
"OutlinedToolButtonBase {\n"
"    padding: 8px 9px 9px 8px;\n"
"}\n"
"\n"
"OutlinedPushButtonBase:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"}\n"
"\n"
"OutlinedPushButtonBase:disabled {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"}\n"
"\n"
"OutlinedPushButtonBase[hasIcon=false] {\n"
"    padding: 6px 10px 6px 10px;\n"
"}\n"
"\n"
"OutlinedPushButtonBase[hasIcon=true] {\n"
"    padding: 6px 10px 6px 26px;\n"
"}\n"
"\n"
"OutlinedPushButtonBase:checked {\n"
"    color: white;\n"
"}\n"
"\n"
"OutlinedPushButtonBase:checked:pressed {\n"
"    color: rgba(255, 255, 255, 0.63);\n"
"}\n"
"\n"
"OutlinedPushButton:checked,\n"
"OutlinedPushButton:checked:pressed {\n"
"    color: #009faa;\n"
"}\n"
"\n"
"Chip[isClosable=true][hasIcon=false] {\n"
"    padding: 5px 32px 5px 10px;\n"
"}\n"
"\n"
"Chip[isClosable=true][hasIcon=true] {\n"
"    padding: 5px 32px 5px 33px;\n"
"}\n"
"\n"
"Chip[isClosable=false][hasIcon=false] {\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"Chip[isClosable=false][hasIcon=true] {\n"
"    padding: 5px 10px 5px 33px;\n"
"}\n"
"\n"
"FilledPushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"FilledPushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"FilledPushButton {\n"
"    color: white;\n"
"}\n"
"\n"
"FilledToolButton {\n"
"    padding: 5px 9px 6px 8px;\n"
"}\n"
"\n"
"FilledPushButton:pressed {\n"
"    color: rgba(255, 255, 255, 0.786);\n"
"}\n"
"\n"
"FilledPushButton:disabled {\n"
"    color: rgba(255, 255, 255, 0.36);\n"
"}\n"
"\n"
"TextPushButton {\n"
"    color: black;\n"
"    background: transparent;\n"
"    border-radius: 5px;\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"    border: none;\n"
"}\n"
"\n"
"TextPushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"TextPushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"TextPushButton[level=\"Error\"] {\n"
"    color: #cf1010;\n"
"}\n"
"\n"
"TextPushButton[level=\"Warning\"] {\n"
"    color: #875101;\n"
"}\n"
"\n"
"TextPushButton[level=\"Success\"] {\n"
"    color: #026f02;\n"
"}\n"
"\n"
"TextPushButton[level=\"Attension\"] {\n"
"    color: #009faa;\n"
"}\n"
"\n"
"TextPushButton:hover{\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"TextPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"}\n"
"\n"
"TextPushButton:disabled {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"Tag[hasIcon=false] {\n"
"    padding: 5px 8px 5px 8px;\n"
"}\n"
"\n"
"Tag[hasIcon=true] {\n"
"    padding: 5px 8px 5px 31px;\n"
"}\n"
"\n"
"RoundPushButton[hasIcon=false] {\n"
"    padding: 7px 24px 7px 24px;\n"
"}\n"
"\n"
"RoundPushButton[hasIcon=true] {\n"
"    padding: 7px 16px 7px 33px;\n"
"}")
        self.PushButton_create.setObjectName("PushButton_create")
        self.horizontalLayout.addWidget(self.PushButton_create)
        self.PushButton_cancel = PushButton(Dialog_AddProperty)
        self.PushButton_cancel.setObjectName("PushButton_cancel")
        self.horizontalLayout.addWidget(self.PushButton_cancel)
        self.verticalLayout_6.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_AddProperty)
        self.PushButton_cancel.clicked.connect(Dialog_AddProperty.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_AddProperty)

    def retranslateUi(self, Dialog_AddProperty):
        _translate = QtCore.QCoreApplication.translate
        Dialog_AddProperty.setWindowTitle(_translate("Dialog_AddProperty", "Dialog"))
        self.label_title.setText(_translate("Dialog_AddProperty", "title"))
        self.label_des.setText(_translate("Dialog_AddProperty", "description"))
        self.label_bed.setText(_translate("Dialog_AddProperty", "bedroom"))
        self.label_bath.setText(_translate("Dialog_AddProperty", "bathroom"))
        self.label_size.setText(_translate("Dialog_AddProperty", "size"))
        self.label_price.setText(_translate("Dialog_AddProperty", "Price"))
        self.label_seller.setText(_translate("Dialog_AddProperty", "seller"))
        self.PushButton_create.setText(_translate("Dialog_AddProperty", "Create"))
        self.PushButton_cancel.setText(_translate("Dialog_AddProperty", "Cancel"))
from qfluentwidgets import LineEdit, PushButton
from qfluentwidgetspro import FilledPushButton
