# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AgentMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgentMenu(object):
    def setupUi(self, AgentMenu):
        AgentMenu.setObjectName("AgentMenu")
        AgentMenu.resize(1309, 915)
        AgentMenu.setMinimumSize(QtCore.QSize(1200, 830))
        self.centralwidget = QtWidgets.QWidget(AgentMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_nev = QtWidgets.QWidget(self.centralwidget)
        self.widget_nev.setGeometry(QtCore.QRect(140, 120, 171, 461))
        self.widget_nev.setStyleSheet("background-color: #2596be;\n"
"\n"
"border-top-left-radius:30;\n"
"border-bottom-left-radius:30px;")
        self.widget_nev.setObjectName("widget_nev")
        self.pushButton_list = QtWidgets.QPushButton(self.widget_nev)
        self.pushButton_list.setGeometry(QtCore.QRect(20, 140, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pushButton_list.setFont(font)
        self.pushButton_list.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/white/icons/white/clipboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_list.setIcon(icon)
        self.pushButton_list.setObjectName("pushButton_list")
        self.pushButton_profile = QtWidgets.QPushButton(self.widget_nev)
        self.pushButton_profile.setGeometry(QtCore.QRect(10, 200, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pushButton_profile.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/white/icons/white/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_profile.setIcon(icon1)
        self.pushButton_profile.setObjectName("pushButton_profile")
        self.pushButton_review = QtWidgets.QPushButton(self.widget_nev)
        self.pushButton_review.setGeometry(QtCore.QRect(20, 320, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pushButton_review.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/white/icons/white/award.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_review.setIcon(icon2)
        self.pushButton_review.setObjectName("pushButton_review")
        self.pushButton_create_2 = QtWidgets.QPushButton(self.widget_nev)
        self.pushButton_create_2.setGeometry(QtCore.QRect(10, 260, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pushButton_create_2.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/white/icons/white/activity.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_create_2.setIcon(icon3)
        self.pushButton_create_2.setObjectName("pushButton_create_2")
        self.pushButton_logout = QtWidgets.QPushButton(self.widget_nev)
        self.pushButton_logout.setGeometry(QtCore.QRect(20, 410, 81, 31))
        self.pushButton_logout.setStyleSheet("font: 9pt \"Arial Rounded MT Bold\";")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/white/icons/white/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon4)
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.label_icon = QtWidgets.QLabel(self.widget_nev)
        self.label_icon.setGeometry(QtCore.QRect(50, 20, 61, 51))
        self.label_icon.setStyleSheet("image: url(:/white/icons/white/anchor.svg);")
        self.label_icon.setText("")
        self.label_icon.setObjectName("label_icon")
        self.textEdit_username = QtWidgets.QTextEdit(self.widget_nev)
        self.textEdit_username.setGeometry(QtCore.QRect(30, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.textEdit_username.setFont(font)
        self.textEdit_username.setObjectName("textEdit_username")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(310, 180, 641, 401))
        self.stackedWidget.setStyleSheet("border-bottom-right-radius:30px;\n"
"background-color: rgb(247, 247, 247);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_profile = QtWidgets.QWidget()
        self.page_profile.setObjectName("page_profile")
        self.label_title_2 = QtWidgets.QLabel(self.page_profile)
        self.label_title_2.setGeometry(QtCore.QRect(50, 20, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_title_2.setFont(font)
        self.label_title_2.setStyleSheet("background-color: rgb(161, 210, 255);\n"
"\n"
"border-top-left-radius:30;\n"
"border-bottom-left-radius:30px;\n"
"\n"
"border-top-right-radius:30;\n"
"border-bottom-right-radius:30px;")
        self.label_title_2.setObjectName("label_title_2")
        self.TextEdit_title_2 = TextEdit(self.page_profile)
        self.TextEdit_title_2.setGeometry(QtCore.QRect(190, 30, 151, 41))
        self.TextEdit_title_2.setObjectName("TextEdit_title_2")
        self.label_title_3 = QtWidgets.QLabel(self.page_profile)
        self.label_title_3.setGeometry(QtCore.QRect(50, 100, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_title_3.setFont(font)
        self.label_title_3.setStyleSheet("background-color: rgb(161, 210, 255);\n"
"\n"
"border-top-left-radius:30;\n"
"border-bottom-left-radius:30px;\n"
"\n"
"border-top-right-radius:30;\n"
"border-bottom-right-radius:30px;")
        self.label_title_3.setObjectName("label_title_3")
        self.TextEdit_title_3 = TextEdit(self.page_profile)
        self.TextEdit_title_3.setGeometry(QtCore.QRect(160, 110, 191, 41))
        self.TextEdit_title_3.setObjectName("TextEdit_title_3")
        self.stackedWidget.addWidget(self.page_profile)
        self.page_create = QtWidgets.QWidget()
        self.page_create.setObjectName("page_create")
        self.label_title = QtWidgets.QLabel(self.page_create)
        self.label_title.setGeometry(QtCore.QRect(30, 20, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("background-color: rgb(161, 210, 255);\n"
"\n"
"border-top-left-radius:30;\n"
"border-bottom-left-radius:30px;\n"
"\n"
"border-top-right-radius:30;\n"
"border-bottom-right-radius:30px;")
        self.label_title.setObjectName("label_title")
        self.TextEdit_title = TextEdit(self.page_create)
        self.TextEdit_title.setGeometry(QtCore.QRect(100, 30, 341, 41))
        self.TextEdit_title.setObjectName("TextEdit_title")
        self.label_bed = QtWidgets.QLabel(self.page_create)
        self.label_bed.setGeometry(QtCore.QRect(30, 100, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_bed.setFont(font)
        self.label_bed.setStyleSheet("background-color: rgb(161, 210, 255);\n"
"\n"
"border-top-left-radius:30;\n"
"border-bottom-left-radius:30px;\n"
"\n"
"border-top-right-radius:30;\n"
"border-bottom-right-radius:30px;")
        self.label_bed.setObjectName("label_bed")
        self.TextEdit_bed = TextEdit(self.page_create)
        self.TextEdit_bed.setGeometry(QtCore.QRect(130, 110, 61, 41))
        self.TextEdit_bed.setObjectName("TextEdit_bed")
        self.label_bath = QtWidgets.QLabel(self.page_create)
        self.label_bath.setGeometry(QtCore.QRect(250, 100, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_bath.setFont(font)
        self.label_bath.setStyleSheet("background-color: rgb(161, 210, 255);\n"
"\n"
"border-top-left-radius:30;\n"
"border-bottom-left-radius:30px;\n"
"\n"
"border-top-right-radius:30;\n"
"border-bottom-right-radius:30px;")
        self.label_bath.setObjectName("label_bath")
        self.TextEdit_bath = TextEdit(self.page_create)
        self.TextEdit_bath.setGeometry(QtCore.QRect(360, 110, 61, 41))
        self.TextEdit_bath.setObjectName("TextEdit_bath")
        self.label_size = QtWidgets.QLabel(self.page_create)
        self.label_size.setGeometry(QtCore.QRect(470, 100, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_size.setFont(font)
        self.label_size.setStyleSheet("background-color: rgb(161, 210, 255);\n"
"\n"
"border-top-left-radius:30;\n"
"border-bottom-left-radius:30px;\n"
"\n"
"border-top-right-radius:30;\n"
"border-bottom-right-radius:30px;")
        self.label_size.setObjectName("label_size")
        self.TextEdit_size = TextEdit(self.page_create)
        self.TextEdit_size.setGeometry(QtCore.QRect(530, 110, 61, 41))
        self.TextEdit_size.setObjectName("TextEdit_size")
        self.label_price = QtWidgets.QLabel(self.page_create)
        self.label_price.setGeometry(QtCore.QRect(30, 180, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_price.setFont(font)
        self.label_price.setStyleSheet("background-color: rgb(161, 210, 255);\n"
"\n"
"border-top-left-radius:30;\n"
"border-bottom-left-radius:30px;\n"
"\n"
"border-top-right-radius:30;\n"
"border-bottom-right-radius:30px;")
        self.label_price.setObjectName("label_price")
        self.TextEdit_price = TextEdit(self.page_create)
        self.TextEdit_price.setGeometry(QtCore.QRect(100, 190, 151, 41))
        self.TextEdit_price.setObjectName("TextEdit_price")
        self.label_status = QtWidgets.QLabel(self.page_create)
        self.label_status.setGeometry(QtCore.QRect(290, 180, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("background-color: rgb(161, 210, 255);\n"
"\n"
"border-top-left-radius:30;\n"
"border-bottom-left-radius:30px;\n"
"\n"
"border-top-right-radius:30;\n"
"border-bottom-right-radius:30px;")
        self.label_status.setObjectName("label_status")
        self.RadioButton_not_ava = RadioButton(self.page_create)
        self.RadioButton_not_ava.setGeometry(QtCore.QRect(370, 200, 113, 24))
        self.RadioButton_not_ava.setObjectName("RadioButton_not_ava")
        self.RadioButton_2 = RadioButton(self.page_create)
        self.RadioButton_2.setGeometry(QtCore.QRect(462, 200, 131, 24))
        self.RadioButton_2.setObjectName("RadioButton_2")
        self.label_agent = QtWidgets.QLabel(self.page_create)
        self.label_agent.setGeometry(QtCore.QRect(30, 260, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_agent.setFont(font)
        self.label_agent.setStyleSheet("background-color: rgb(161, 210, 255);\n"
"\n"
"border-top-left-radius:30;\n"
"border-bottom-left-radius:30px;\n"
"\n"
"border-top-right-radius:30;\n"
"border-bottom-right-radius:30px;")
        self.label_agent.setObjectName("label_agent")
        self.TextEdit_agent = TextEdit(self.page_create)
        self.TextEdit_agent.setGeometry(QtCore.QRect(150, 270, 141, 41))
        self.TextEdit_agent.setObjectName("TextEdit_agent")
        self.label_seller = QtWidgets.QLabel(self.page_create)
        self.label_seller.setGeometry(QtCore.QRect(330, 260, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_seller.setFont(font)
        self.label_seller.setStyleSheet("background-color: rgb(161, 210, 255);\n"
"\n"
"border-top-left-radius:30;\n"
"border-bottom-left-radius:30px;\n"
"\n"
"border-top-right-radius:30;\n"
"border-bottom-right-radius:30px;")
        self.label_seller.setObjectName("label_seller")
        self.TextEdit_seller = TextEdit(self.page_create)
        self.TextEdit_seller.setGeometry(QtCore.QRect(450, 270, 141, 41))
        self.TextEdit_seller.setObjectName("TextEdit_seller")
        self.pushButton_create = QtWidgets.QPushButton(self.page_create)
        self.pushButton_create.setGeometry(QtCore.QRect(170, 340, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.pushButton_create.setFont(font)
        self.pushButton_create.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(158, 164, 255);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"    border:2px solid rgb(158, 164, 255);\n"
"\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:5pax;\n"
"    padding-left:5pax;\n"
"}")
        self.pushButton_create.setObjectName("pushButton_create")
        self.stackedWidget.addWidget(self.page_create)
        self.page_review = QtWidgets.QWidget()
        self.page_review.setObjectName("page_review")
        self.label_review = QtWidgets.QLabel(self.page_review)
        self.label_review.setGeometry(QtCore.QRect(20, 10, 171, 41))
        self.label_review.setStyleSheet("font: 9pt \"Arial Rounded MT Bold\";")
        self.label_review.setObjectName("label_review")
        self.ListWidget_review = ListWidget(self.page_review)
        self.ListWidget_review.setGeometry(QtCore.QRect(20, 70, 581, 301))
        self.ListWidget_review.setObjectName("ListWidget_review")
        self.stackedWidget.addWidget(self.page_review)
        self.page_list = QtWidgets.QWidget()
        self.page_list.setObjectName("page_list")
        self.ListWidget_list = ListWidget(self.page_list)
        self.ListWidget_list.setGeometry(QtCore.QRect(20, 70, 581, 301))
        self.ListWidget_list.setObjectName("ListWidget_list")
        self.label_list = QtWidgets.QLabel(self.page_list)
        self.label_list.setGeometry(QtCore.QRect(20, 10, 171, 41))
        self.label_list.setStyleSheet("font: 9pt \"Arial Rounded MT Bold\";")
        self.label_list.setObjectName("label_list")
        self.stackedWidget.addWidget(self.page_list)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(310, 120, 641, 61))
        self.widget_2.setStyleSheet("border-top-right-radius:30;\n"
"background-color: rgb(247, 247, 247);")
        self.widget_2.setObjectName("widget_2")
        self.label_dash = QtWidgets.QLabel(self.widget_2)
        self.label_dash.setGeometry(QtCore.QRect(60, 10, 101, 41))
        self.label_dash.setStyleSheet("font: 9pt \"Arial Rounded MT Bold\";")
        self.label_dash.setObjectName("label_dash")
        self.pushButton_nev = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_nev.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.pushButton_nev.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/blue/icons/blue/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_nev.setIcon(icon5)
        self.pushButton_nev.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_nev.setObjectName("pushButton_nev")
        self.pushButton_max = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_max.setGeometry(QtCore.QRect(590, 10, 41, 41))
        self.pushButton_max.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/blue/icons/blue/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_max.setIcon(icon6)
        self.pushButton_max.setIconSize(QtCore.QSize(40, 35))
        self.pushButton_max.setObjectName("pushButton_max")
        self.pushButton_min = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_min.setGeometry(QtCore.QRect(540, 10, 41, 41))
        self.pushButton_min.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/blue/icons/blue/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min.setIcon(icon7)
        self.pushButton_min.setIconSize(QtCore.QSize(40, 35))
        self.pushButton_min.setObjectName("pushButton_min")
        self.SubtitleLabel_welcome = SubtitleLabel(self.widget_2)
        self.SubtitleLabel_welcome.setGeometry(QtCore.QRect(190, 0, 281, 51))
        self.SubtitleLabel_welcome.setObjectName("SubtitleLabel_welcome")
        AgentMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(AgentMenu)
        self.stackedWidget.setCurrentIndex(3)
        self.pushButton_min.clicked.connect(AgentMenu.showMinimized) # type: ignore
        self.pushButton_max.clicked.connect(AgentMenu.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AgentMenu)

    def retranslateUi(self, AgentMenu):
        _translate = QtCore.QCoreApplication.translate
        AgentMenu.setWindowTitle(_translate("AgentMenu", "MainWindow"))
        self.pushButton_list.setText(_translate("AgentMenu", "Property list"))
        self.pushButton_profile.setText(_translate("AgentMenu", "My profile"))
        self.pushButton_review.setText(_translate("AgentMenu", "Check review"))
        self.pushButton_create_2.setText(_translate("AgentMenu", "Create list"))
        self.pushButton_logout.setText(_translate("AgentMenu", "log out"))
        self.textEdit_username.setPlaceholderText(_translate("AgentMenu", "user name"))
        self.label_title_2.setText(_translate("AgentMenu", "     My user name:"))
        self.label_title_3.setText(_translate("AgentMenu", "     My Email:"))
        self.label_title.setText(_translate("AgentMenu", "     Title:"))
        self.label_bed.setText(_translate("AgentMenu", "    Bedrooms:"))
        self.label_bath.setText(_translate("AgentMenu", "    Bathrooms:"))
        self.label_size.setText(_translate("AgentMenu", "   size:"))
        self.label_price.setText(_translate("AgentMenu", "     Price:"))
        self.label_status.setText(_translate("AgentMenu", "   Status:"))
        self.RadioButton_not_ava.setText(_translate("AgentMenu", "Availabe"))
        self.RadioButton_2.setText(_translate("AgentMenu", "not Availabe"))
        self.label_agent.setText(_translate("AgentMenu", "   Agent Name:"))
        self.label_seller.setText(_translate("AgentMenu", "   Seller Name:"))
        self.pushButton_create.setText(_translate("AgentMenu", "Create"))
        self.label_review.setText(_translate("AgentMenu", "Your Reviews:"))
        self.label_list.setText(_translate("AgentMenu", "Your property list:"))
        self.label_dash.setText(_translate("AgentMenu", "Dashboard"))
        self.SubtitleLabel_welcome.setText(_translate("AgentMenu", "Find your dream home today"))
from qfluentwidgets import ListWidget, RadioButton, SubtitleLabel, TextEdit
import res_rc
